### ISSUE TITLE
pokemon.jsに捕まえたポケモンの数を保持する仕組みがほしい

### ISSUE THREAD

**Issue by usagi-f** [usagi-f/togoshi-bot#2]
捕まえたポケモンのIDを保持して、現在捕まえた数（＝ポケモン図鑑どれだけ埋まったか的な）が見たい。

普通に変数で持つだけだとデプロイのたびに初期化されそう…？

-> サーバーレスに実現したい 😣

**Comment by kamome-no-sora** [comment]
`get pokemon` のコードを拝借して自分のbotにいじって色々やってみました。
`robot.brain` を使えば捕まえた数、捕まえたポケモンの情報を保持できた（デプロイしても初期化されない）ので、結構良さげでした。

**Comment by usagi-f** [comment]
`robot.brain` で少し書き進めてみました。

---

https://github.com/usagi-f/togoshi-bot/blob/feature/2-pokemon-zukan/src/pokemon.js#L54
取得したデータが未保存のidだった場合、配列にpushして、brainにsetします。

![2016-10-07 20 05 02](https://cloud.githubusercontent.com/assets/9045135/19187939/6f1ce3ac-8cc9-11e6-8bf4-80e3776440a4.png)

---

https://github.com/usagi-f/togoshi-bot/blob/feature/2-pokemon-zukan/src/pokemon.js#L74
`robot.respond(/check zukan/,`

何匹捕まえたか確認

---

https://github.com/usagi-f/togoshi-bot/blob/feature/2-pokemon-zukan/src/pokemon.js#L84
`robot.respond(/check pokemon (.*)/i,`

指定した名称のポケモンをすでに捕まえているか確認

---

突貫でつくったのでまだプルリクにはしてません。

すでに捕まえているポケモンだった場合CPを比較して、新しい方が上だった場合は値を更新したいなぁと思いました。

あと、ローカルで再起動したらデータもクリアされたけれど、deployだと大丈夫なのか？
[robot.brain を永続化する Hubot スクリプトをつくろう](http://qiita.com/bouzuya/items/ae1cb5610a64794bc522)

データ保持周りはもうちょっとちゃんと考えたほうがいいのかも。
