### ISSUE TITLE
ハイフン以降の一括削除による画像取得ミス

### ISSUE THREAD

**Issue by usagi-f** [usagi-f/togoshi-bot#27]
https://github.com/usagi-f/togoshi-bot/blob/master/src/pokemon/libs.js#L35

形態変化時の対応をした影響で、一部のポケモンの画像取得ができなくなった

>[20:04] 
CP2093のニドラン♀を捕まえたゴシ！
http://www.pokestadium.com/sprites/xy/nidoran.gif

**Comment by loose-art** [comment]
デオキシス等も画像取得できてませんでした。
一度名前をすべて洗い出します。
