### ISSUE TITLE
get pokemonを更に拡張しやすい作りに整理したい

### ISSUE THREAD

**Issue by pikoshimame** [usagi-f/togoshi-bot#32]
pokemon.js
pokemon/constants.js
pokemon/libs.js
を今後の拡張に備えて、より疎結合な作りにしたい。

**Comment by usagi-f** [comment]
もうちょい具体的にお願いします…

**Comment by pikoshimame** [comment]
今後機能拡張を見越して、
・APIでポケモン取得
・取得したポケモンを元にslackに流すデータ（文言）を作成
・slackにデータを送信
・取得したポケモンをDBに保存
はそれぞれある程度分離しておいた方が良いと思いますがどうでしょう。

**Comment by usagi-f** [comment]
ごもっともだと思いますが、具体的なものがないので（何を使って分離するのか？どのコードとどのコードを分離するのか？）
直接PRから提案してくれると嬉しいです。

一応ある程度は既に分離されてる認識です。

**Comment by pikoshimame** [comment]
了解です！コードリファクタリングしてPRしますね！

**Comment by pikoshimame** [comment]
#43 
一旦途中経過ですがPRしました。
こういった形でclass化して分離していくのはどうだろうという提案です。
ご意見頂きたいです。
