### ISSUE TITLE
mention指定だとzukanが動作しない

### ISSUE THREAD

**Issue by usagi-f** [usagi-f/togoshi-bot#35]
https://github.com/usagi-f/togoshi-bot/blob/master/src/pokemon.js#L43

おそらくここの判定が微妙なせい

**Comment by abcdarts** [comment]
`@` が必要なのでは。。。？

**Comment by usagi-f** [comment]
DMで `zukan pokemon` とだけ打つと、 `togoshi-bot zukan pokemon` が格納されるので
単純に記述した文言ではないようです。
