### ISSUE TITLE
0匹時の文言をいい感じにする

### ISSUE THREAD

**Issue by abcdarts** [usagi-f/togoshi-bot#36]
![myu](https://user-images.githubusercontent.com/12826191/28564845-4be203fa-7165-11e7-9052-8b74ee5b83a1.png)

例えば上記の場合は `ミュウはまだ捕まえてないゴシ...` みたいにしたい

**Comment by usagi-f** [comment]
https://github.com/usagi-f/togoshi-bot/pull/41
